#cloud-config

locale: en_US.UTF-8

users:
- name: test
  lock-passwd: false
  lock_passwd: false
  plain_text_passwd: test
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
    - ssh-rsa xxxxxxx

runcmd:
  - mkdir -p /run/attestation
  - cd /run/attestation
  - hostname > hostname
  - cp /etc/ssh/ssh_host_rsa_key.pub .
  - cp /home/test/.ssh/authorized_keys guest_owner.pub
  - ip -brief -family inet address show scope global | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" > address
  - cat ssh_host_rsa_key.pub guest_owner.pub address > pubkeys
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib64/
  - sev-guest-get-report -f pubkeys -x guest_report.bin >conslog 2>&1
# Uncomment the following line to see an attestation failure.
#  - dd if=/dev/random of=guest_report.bin bs=4 count=1 conv=notrunc
  - tar -cvf guest-report.tar *.cert guest_report.bin hostname pubkeys address conslog
  - /usr/local/bin/upload-guest-report.sh guest-report.tar
  - rm -f /usr/local/bin/upload-guest-report.sh

write_files:
  - path: /usr/local/bin/upload-guest-report.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      server="http://100.64.0.200/cgi-bin/ssh-key-exchange.sh"
      content="Content-Type:application/octet-stream"
      curl --data-binary @${1} -H ${content} ${server}
